spring.application.name=visa-holder-tracker
server.port=9000

# Enables the health actuator
management.endpoints.web.exposure.include=health

# Set to always show full health details
management.endpoint.health.show-details=always