spring.application.name=visa-holder-tracker
server.port=9000

# H2 config for local testing
spring.datasource.url=jdbc:h2:mem:visadb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.security.ignored=/h2-console/**
# http://localhost:9000/h2-console
# Won't work without the security config

# Enables the health actuator
management.endpoints.web.exposure.include=health

# Set to always show full health details
management.endpoint.health.show-details=always

# Health actuator url
# http://localhost:9000/actuator/health

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Used to temp remove warning in tests
spring.data.web.pageable.default-page-size=10

# Tells Spring to look for data-postgres.sql
spring.sql.init.platform=h2

# Use a signed key not JWT token
jwt.secretkey=sPNg5jiHKH3tflmI4c3z0b3FQlmfHVFuYX1W0ZTrU/8=

# AWS
aws.region=eu-west-2
aws.s3.bucket=visa-holder-reports
aws.sqs.queue-url=https://sqs.eu-west-2.amazonaws.com/158648291264/visa-violations
aws.profile=default

# Configures Swagger UI to show the Authorize button
springdoc.open-api.security[0].bearerAuth=
springdoc.open-api.components.securitySchemes.bearerAuth.type=http
springdoc.open-api.components.securitySchemes.bearerAuth.scheme=bearer
springdoc.open-api.components.securitySchemes.bearerAuth.bearerFormat=JWT

# Swagger url
# http://localhost:9000/swagger-ui/index.html
