spring.application.name=visa-holder-tracker
server.port=9000

jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3OTg5NzI1MywiZXhwIjoxNzc5ODk3NTUzfQ.b-Kqss4Ey0p1PXbTrc92BEfyNOyjun1ur7cXMMClzcg